---
name: Egg-Plugin-SessionKit-Auth
version: 2.01
author:
  - 'Masatoshi Mizuno E<lt>mizunoE<64>bomcity.comE<gt>'
abstract: Authentication of session base.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Egg::Model::DBIC: 2
  Egg::Plugin::Crypt::CBC: 2
  Egg::Plugin::SessionKit: 2
  Egg::Release: 2
  Test::Perl::Critic: 0
  Test::Pod: 0
  Test::Pod::Coverage: 0
  Test::Simple: 0
provides:
  Egg::Plugin::SessionKit::Auth:
    file: lib/Egg/Plugin/SessionKit/Auth.pm
    version: 2.01
  Egg::Plugin::SessionKit::Auth::Crypt::CBC:
    file: lib/Egg/Plugin/SessionKit/Auth/Crypt/CBC.pm
    version: 2.01
  Egg::Plugin::SessionKit::Auth::Crypt::MD5:
    file: lib/Egg/Plugin/SessionKit/Auth/Crypt/MD5.pm
    version: 2.01
  Egg::Plugin::SessionKit::Auth::Crypt::Plain:
    file: lib/Egg/Plugin/SessionKit/Auth/Crypt/Plain.pm
    version: 2.01
  Egg::Plugin::SessionKit::Auth::DBI:
    file: lib/Egg/Plugin/SessionKit/Auth/DBI.pm
    version: 2.01
  Egg::Plugin::SessionKit::Auth::DBI::handler:
    file: lib/Egg/Plugin/SessionKit/Auth/DBI.pm
  Egg::Plugin::SessionKit::Auth::DBIC:
    file: lib/Egg/Plugin/SessionKit/Auth/DBIC.pm
    version: 2.01
  Egg::Plugin::SessionKit::Auth::DBIC::handler:
    file: lib/Egg/Plugin/SessionKit/Auth/DBIC.pm
  Egg::Plugin::SessionKit::Auth::File:
    file: lib/Egg/Plugin/SessionKit/Auth/File.pm
    version: 2.01
  Egg::Plugin::SessionKit::Auth::File::handler:
    file: lib/Egg/Plugin/SessionKit/Auth/File.pm
  Egg::Plugin::SessionKit::Auth::handler:
    file: lib/Egg/Plugin/SessionKit/Auth.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
