abstract: The authentication function is offered by using the session.
author: Masatoshi Mizuno <lusheE<64>cpan.org>
build_requires: 
  Test::More: 0
  Test::Pod: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Egg-Plugin-SessionKit-Auth
no_index: 
  directory: 
    - inc
    - t
requires: 
  DBIx::Class: 0.07999
  Egg::Model::DBIC: 0.03
  Egg::Plugin::Crypt::CBC: 0.01
  Egg::Plugin::SessionKit: 0.07
  Egg::Release: 1.13
version: 0.06
